import { useState } from 'react';
import { Video, Zap, Loader2, Check, FileText, Download, Lock } from 'lucide-react';
import jsPDF from 'jspdf';

interface VideoRequestFormProps {
    requestTitle: string;
    setRequestTitle: (val: string) => void;
    requestStyle: string;
    setRequestStyle: (val: string) => void;
    requestDuration: string;
    setRequestDuration: (val: string) => void;
    requestTone: string;
    setRequestTone: (val: string) => void;
    requestNotes: string;
    setRequestNotes: (val: string) => void;
    submittingRequest: boolean;
    handleSubmitVideoRequest: (scriptContent?: string) => void; // Updated to accept script
    videoRequests: any[];
    tier: string;
    credits: number; // Main credits
}

export default function VideoRequestForm({
    requestTitle,
    setRequestTitle,
    requestStyle,
    setRequestStyle,
    requestDuration,
    setRequestDuration,
    requestTone,
    setRequestTone,
    requestNotes,
    setRequestNotes,
    submittingRequest,
    handleSubmitVideoRequest,
    videoRequests,
    tier,
    credits
}: VideoRequestFormProps) {
    const [generatingScript, setGeneratingScript] = useState(false);
    const [generatedScript, setGeneratedScript] = useState('');

    const isFree = tier === 'Free';
    const monthlyAllowance = tier === 'Diamond' ? 3 : tier === 'Solitaire' ? 5 : 0;

    const handleGenerateScript = async () => {
        if (isFree) {
            alert("Please upgrade to Diamond or Solitaire to generate video scripts.");
            return;
        }
        if (!requestTitle) {
            alert("Please enter a title first.");
            return;
        }
        setGeneratingScript(true);
        try {
            // Construct query parameters for the Python endpoint
            const params = new URLSearchParams({
                title: requestTitle,
                duration: requestDuration,
                tone: requestTone,
                notes: requestNotes
            });

            const res = await fetch(`/api/py/m3/generate-script?${params.toString()}`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' }
            });

            if (!res.ok) throw new Error('Generation failed');

            const data = await res.json();
            setGeneratedScript(data.script);
        } catch (e) {
            alert("Failed to generate script. Please try again.");
        } finally {
            setGeneratingScript(false);
        }
    };

    const handleDownloadPDF = () => {
        if (!generatedScript) return;
        const doc = new jsPDF();

        // Branding
        doc.setFillColor(147, 51, 234); // Purple
        doc.rect(0, 0, 210, 20, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(16);
        doc.setFont("helvetica", "bold");
        doc.text("Agentic Eye | AI Video Script", 10, 13);

        // Content
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(14);
        doc.text(`Title: ${requestTitle}`, 10, 40);

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`Duration: ${requestDuration} | Tone: ${requestTone}`, 10, 48);

        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
        const splitText = doc.splitTextToSize(generatedScript, 180);
        doc.text(splitText, 10, 60);

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text("Generated by Agentic Eye AI", 10, 280);

        doc.save(`${requestTitle.replace(/\s+/g, '_')}_script.pdf`);
    };

    // Wrapper to include script in the submission
    const handleSave = async () => {
        // Pass the generated script to the parent handler
        handleSubmitVideoRequest(generatedScript);
    };

    return (
        <div className="max-w-6xl mx-auto">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                {/* Request Form */}
                <div className="relative">
                    <div className={`bg-white rounded-2xl shadow-sm border border-gray-200 p-8 ${isFree ? 'blur-sm select-none pointer-events-none' : ''}`}>
                        <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-2">
                            <Video className="w-6 h-6 text-purple-600" />
                            AI Video Generator
                        </h2>

                        <div className="space-y-6">
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-2">Idea Title</label>
                                <input
                                    type="text"
                                    value={requestTitle}
                                    onChange={(e) => setRequestTitle(e.target.value)}
                                    placeholder="e.g., Top 5 AI Tools for 2025"
                                    className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:ring-2 focus:ring-purple-500 focus:border-transparent outline-none transition-all"
                                />
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-2">Style</label>
                                    <select
                                        value={requestStyle}
                                        onChange={(e) => setRequestStyle(e.target.value)}
                                        className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:ring-2 focus:ring-purple-500 outline-none"
                                    >
                                        <option>Fast-paced</option>
                                        <option>Minimalist</option>
                                        <option>Documentary</option>
                                        <option>Cinematic</option>
                                        <option>Vlog Style</option>
                                        <option>Corporate</option>
                                    </select>
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-2">Duration</label>
                                    <select
                                        value={requestDuration}
                                        onChange={(e) => setRequestDuration(e.target.value)}
                                        className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:ring-2 focus:ring-purple-500 outline-none"
                                    >
                                        <option>30s</option>
                                        <option>60s</option>
                                        <option>90s</option>
                                        <option>2 mins</option>
                                        <option>Custom</option>
                                    </select>
                                </div>
                                <div className="col-span-2">
                                    <label className="block text-sm font-medium text-gray-700 mb-2">Voice Tone</label>
                                    <select
                                        value={requestTone}
                                        onChange={(e) => setRequestTone(e.target.value)}
                                        className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:ring-2 focus:ring-purple-500 outline-none"
                                    >
                                        <option>Energetic & Hype</option>
                                        <option>Professional & Calm</option>
                                        <option>Storyteller</option>
                                        <option>Funny & Sarcastic</option>
                                        <option>Inspirational</option>
                                    </select>
                                </div>
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-2">Additional Notes</label>
                                <textarea
                                    value={requestNotes}
                                    onChange={(e) => setRequestNotes(e.target.value)}
                                    placeholder="Any specific instructions..."
                                    rows={3}
                                    className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:ring-2 focus:ring-purple-500 focus:border-transparent outline-none transition-all resize-none"
                                />
                            </div>

                            <div className="bg-purple-50 p-4 rounded-lg flex items-center justify-between">
                                <span className="text-sm text-purple-700 font-medium">Cost per video</span>
                                <span className="text-sm font-bold text-purple-900">10 Credits</span>
                            </div>

                            {/* AI Generation Section */}
                            <div className="pt-4 border-t border-gray-100">
                                {!generatedScript ? (
                                    <button
                                        onClick={handleGenerateScript}
                                        disabled={generatingScript}
                                        className="w-full py-3 bg-gradient-to-r from-purple-600 to-pink-600 text-white font-bold rounded-lg shadow-lg hover:shadow-xl transition-all disabled:opacity-50 flex items-center justify-center gap-2"
                                    >
                                        {generatingScript ? <Loader2 className="animate-spin w-5 h-5" /> : <Zap className="w-5 h-5" />}
                                        Generate Script (AI)
                                    </button>
                                ) : (
                                    <div className="space-y-4 animate-in fade-in slide-in-from-bottom-4 duration-500">
                                        <div className="bg-gray-50 p-4 rounded-xl border border-gray-200 max-h-60 overflow-y-auto">
                                            <div className="flex justify-between items-center mb-2">
                                                <span className="text-xs font-bold text-gray-500 uppercase">Generated Script</span>
                                                <button onClick={handleDownloadPDF} className="text-purple-600 hover:text-purple-700 text-xs font-bold flex items-center gap-1">
                                                    <Download className="w-3 h-3" /> PDF
                                                </button>
                                            </div>
                                            <pre className="whitespace-pre-wrap text-sm text-gray-700 font-sans">{generatedScript}</pre>
                                        </div>
                                        <div className="flex gap-3">
                                            <button
                                                onClick={() => setGeneratedScript('')}
                                                className="flex-1 py-3 bg-gray-100 text-gray-600 font-bold rounded-lg hover:bg-gray-200 transition-colors"
                                            >
                                                Regenerate
                                            </button>
                                            <button
                                                onClick={handleSave}
                                                disabled={submittingRequest}
                                                className="flex-1 py-3 bg-green-500 text-white font-bold rounded-lg shadow-lg hover:bg-green-600 transition-colors flex items-center justify-center gap-2"
                                            >
                                                {submittingRequest ? <Loader2 className="animate-spin w-5 h-5" /> : <Check className="w-5 h-5" />}
                                                Accept & Save
                                            </button>
                                        </div>
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>

                    {isFree && (
                        <div className="absolute inset-0 flex flex-col items-center justify-center z-20 bg-white/50 rounded-2xl">
                            <div className="bg-white p-8 rounded-2xl border border-gray-200 text-center shadow-2xl max-w-sm">
                                <div className="w-16 h-16 bg-purple-100 rounded-full flex items-center justify-center mx-auto mb-4">
                                    <Lock className="w-8 h-8 text-purple-600" />
                                </div>
                                <h3 className="text-xl font-bold text-gray-900 mb-2">Video Generation Locked</h3>
                                <p className="text-gray-500 mb-6">Upgrade to Diamond or Solitaire to unlock AI video script generation and production.</p>
                                <button onClick={() => window.location.href = '/pricing'} className="w-full py-3 bg-gradient-to-r from-purple-600 to-pink-600 text-white font-bold rounded-lg hover:shadow-lg transition-all">
                                    Upgrade Now
                                </button>
                            </div>
                        </div>
                    )}
                </div>

                {/* Request History */}
                <div className="space-y-6">
                    <h3 className="text-xl font-bold text-gray-900">Request History</h3>
                    {videoRequests.length === 0 ? (
                        <div className="text-center py-12 bg-gray-50 rounded-2xl border border-dashed border-gray-300">
                            <Video className="w-12 h-12 text-gray-300 mx-auto mb-3" />
                            <p className="text-gray-500">No video requests yet.</p>
                        </div>
                    ) : (
                        <div className="space-y-4">
                            {videoRequests.map((req) => (
                                <div key={req.id} className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm hover:shadow-md transition-all">
                                    <div className="flex justify-between items-start mb-2">
                                        <h4 className="font-bold text-gray-900">{req.ideaTitle}</h4>
                                        <span className={`px-3 py-1 text-xs font-bold rounded-full ${req.status === 'Completed' ? 'bg-green-100 text-green-700' :
                                            req.status === 'In Progress' ? 'bg-blue-100 text-blue-700' :
                                                'bg-yellow-100 text-yellow-700'
                                            }`}>
                                            {req.status}
                                        </span>
                                    </div>
                                    <p className="text-sm text-gray-500 mb-4 line-clamp-2">{req.notes || 'No additional notes.'}</p>
                                    <div className="flex items-center justify-between text-xs text-gray-400">
                                        <span>{new Date(req.createdAt).toLocaleDateString()}</span>
                                        {req.downloadUrl && (
                                            <a href={req.downloadUrl} target="_blank" rel="noopener noreferrer" className="text-purple-600 font-bold hover:underline">
                                                Download Video
                                            </a>
                                        )}
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
